spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/spring_security
    username: sa
    password:
    driver-class-name: org.h2.Driver
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug